name: Main Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Code Checkout
    - uses: actions/checkout@v3

    - name: Set up Program
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9' 

    - name: Install dependencies
      run: make install

    - name: Run Test
      run: make test
    
    - name: Make Lint
      run: make lint